"""
Stage 6: Code Generation
=========================

Transforms layout specifications into production-ready React code.

Based on Section 5.9 of the specification.
"""

from context import UIBuilderContext, GeneratedFile
from pathlib import Path


# ============================================================================
# CODE TEMPLATES
# ============================================================================

def generate_component_code(context: UIBuilderContext) -> str:
    """
    Generate React component code.
    
    Returns:
        Complete .tsx/.jsx component code
    """
    comp_name = context.component_name
    is_ts = context.uses_typescript
    file_ext = "tsx" if is_ts else "jsx"
    
    # Build imports
    imports = ["import React, { useState } from 'react';"]
    
    # Add Syncfusion imports
    imported_components = set()
    for mapping in context.component_mappings:
        if mapping.package and mapping.component not in imported_components:
            imports.append(f"import {{ {mapping.component} }} from '{mapping.package}';")
            imported_components.add(mapping.component)
    
    # Add styles import
    if context.css_strategy == "css-modules":
        imports.append(f"import styles from './{comp_name}.module.css';")
    
    imports_str = "\n".join(imports)
    
    # Build props interface (TypeScript only)
    props_interface = ""
    if is_ts:
        props_interface = f"""
interface {comp_name}Props {{
  onSubmit?: (data: any) => void;
  className?: string;
}}
"""
    
    # Build state declarations
    state_vars = []
    for field in context.layout_fields:
        if field.type in ["text", "password", "email", "textarea"]:
            state_vars.append(f"  const [{ field.id}, set{field.id.title()}] = useState('');")
        elif field.type == "checkbox":
            state_vars.append(f"  const [{field.id}, set{field.id.title()}] = useState(false);")
    
    state_str = "\n".join(state_vars)
    
    # Build JSX for fields
    jsx_fields = []
    for field in context.layout_fields:
        mapping = next((m for m in context.component_mappings if m.field_id == field.id), None)
        
        if field.type in ["text", "password", "email"]:
            jsx_fields.append(f"""
        <div className={{styles.fieldGroup}}>
          <label htmlFor="{field.id}">
            {field.label}
            {' ' + '<span className={styles.required}>*</span>' if field.required else ''}
          </label>
          <{mapping.component}
            id="{field.id}"
            type="{field.type}"
            value={{{field.id}}}
            change={{(e: any) => set{field.id.title()}(e.value)}}
            placeholder="{field.placeholder or 'Enter ' + field.label.lower()}"
            {'required={true}' if field.required else ''}
          />
        </div>""")
        
        elif field.type == "textarea":
            jsx_fields.append(f"""
        <div className={{styles.fieldGroup}}>
          <label htmlFor="{field.id}">{field.label}</label>
          <{mapping.component}
            id="{field.id}"
            multiline={{true}}
            value={{{field.id}}}
            change={{(e: any) => set{field.id.title()}(e.value)}}
            placeholder="{field.placeholder or field.label}"
          />
        </div>""")
        
        elif field.type == "checkbox":
            jsx_fields.append(f"""
        <{mapping.component}
          id="{field.id}"
          label="{field.label}"
          checked={{{field.id}}}
          change={{(e: any) => set{field.id.title()}(e.checked)}}
        />""")
        
        elif field.type == "button":
            jsx_fields.append(f"""
        <{mapping.component}
          type="submit"
          isPrimary={{true}}
          className={{styles.submitButton}}
        >
          {field.label}
        </{mapping.component}>""")
        
        elif field.type == "link":
            jsx_fields.append(f"""
        <a href="#" className={{styles.link}}>{field.label}</a>""")
        
        elif field.type == "divider":
            jsx_fields.append(f"""
        <div className={{styles.divider}}>
          <span>{field.label}</span>
        </div>""")
    
    jsx_fields_str = "\n".join(jsx_fields)
    
    # Build complete component
    component_code = f"""/**
 * {comp_name} Component
 * 
 * Generated by UI Builder Skill
 * Variant: {context.selected_variant}
 * WCAG 2.1 AA Compliant | Responsive Design | Production Ready
 * 
 * @component
 */

{imports_str}
{props_interface}

export const {comp_name}{': React.FC<' + comp_name + 'Props>' if is_ts else ''} = ({{ onSubmit, className }}) => {{
{state_str}

  const handleSubmit = (e{': React.FormEvent' if is_ts else ''}) => {{
    e.preventDefault();
    
    if (onSubmit) {{
      const data = {{
{chr(10).join([f'        {field.id},' for field in context.layout_fields if field.type not in ['button', 'link', 'divider']])}
      }};
      onSubmit(data);
    }}
  }};

  return (
    <form 
      className={{`${{styles.container}} ${{className || ''}}`}}
      onSubmit={{handleSubmit}}
      aria-label="{context.layout_metadata.get('variant_name', comp_name)}"
    >
      <h1 className={{styles.title}}>
        {context.layout_metadata.get('variant_name', 'Form')}
      </h1>
      
{jsx_fields_str}
    </form>
  );
}};

export default {comp_name};
"""
    
    return component_code


def generate_css_module(context: UIBuilderContext) -> str:
    """
    Generate CSS Module stylesheet.
    
    Returns:
        CSS code
    """
    css = f"""/* {context.component_name}.module.css */
/* Generated by UI Builder Skill */

.container {{
  max-width: 400px;
  margin: 0 auto;
  padding: 2rem;
  background: #ffffff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}}

.title {{
  font-size: 1.5rem;
  font-weight: 600;
  margin-bottom: 1.5rem;
  text-align: center;
  color: #333;
}}

.fieldGroup {{
  margin-bottom: 1rem;
}}

.fieldGroup label {{
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  font-size: 0.875rem;
  color: #555;
}}

.required {{
  color: #d32f2f;
  margin-left: 0.25rem;
}}

.submitButton {{
  width: 100%;
  margin-top: 1rem;
}}

.link {{
  display: inline-block;
  margin-top: 0.5rem;
  color: #1976d2;
  text-decoration: none;
  font-size: 0.875rem;
}}

.link:hover {{
  text-decoration: underline;
}}

.divider {{
  display: flex;
  align-items: center;
  text-align: center;
  margin: 1.5rem 0;
  color: #666;
  font-size: 0.875rem;
}}

.divider::before,
.divider::after {{
  content: '';
  flex: 1;
  border-bottom: 1px solid #ddd;
}}

.divider span {{
  padding: 0 1rem;
}}

/* Responsive Design */
@media (max-width: 768px) {{
  .container {{
    padding: 1.5rem;
    max-width: 100%;
  }}
  
  .title {{
    font-size: 1.25rem;
  }}
}}

@media (max-width: 320px) {{
  .container {{
    padding: 1rem;
  }}
}}
"""
    
    return css


def generate_index_file(context: UIBuilderContext) -> str:
    """
    Generate index.ts barrel export.
    
    Returns:
        Index file code
    """
    comp_name = context.component_name
    file_ext = "tsx" if context.uses_typescript else "jsx"
    
    return f"""export {{ {comp_name}, default }} from './{comp_name}.{file_ext}';
export type {{ {comp_name}Props }} from './{comp_name}.{file_ext}';
"""


# ============================================================================
# MAIN STAGE FUNCTION
# ============================================================================

def generate_code(context: UIBuilderContext) -> UIBuilderContext:
    """
    Stage 6: Generate production-ready React code.
    
    Generates:
    - Component .tsx/.jsx file
    - CSS Module stylesheet (if applicable)
    - Index barrel export
    
    Args:
        context: UIBuilderContext with layout and components defined
    
    Returns:
        Updated context with generated_files populated
    """
    context.current_stage = 6
    
    # Validate prerequisites
    if not context.component_name:
        context.mark_failed("Component name not set. Stage 5 must complete first.")
        return context
    
    if not context.component_mappings:
        context.mark_failed("No component mappings. Stage 4 must complete first.")
        return context
    
    comp_name = context.component_name
    file_ext = "tsx" if context.uses_typescript else "jsx"
    comp_dir = context.component_dir or "src/components"
    
    # Generate component code
    component_code = generate_component_code(context)
    context.generated_files.append(GeneratedFile(
        path=f"{comp_dir}/{comp_name}/{comp_name}.{file_ext}",
        content=component_code,
        type="component",
        language="typescript" if context.uses_typescript else "javascript"
    ))
    
    # Generate CSS if using CSS Modules
    if context.css_strategy == "css-modules":
        css_code = generate_css_module(context)
        context.generated_files.append(GeneratedFile(
            path=f"{comp_dir}/{comp_name}/{comp_name}.module.css",
            content=css_code,
            type="stylesheet",
            language="css"
        ))
    
    # Generate index file
    index_code = generate_index_file(context)
    context.generated_files.append(GeneratedFile(
        path=f"{comp_dir}/{comp_name}/index.ts",
        content=index_code,
        type="index",
        language="typescript"
    ))
    
    return context


if __name__ == "__main__":
    # Test code generation
    from stage_1_intent import analyze_intent
    from stage_2_detection import detect_project
    from stage_3_layout import confirm_layout
    from stage_4_components import pick_components
    from stage_5_preview import generate_preview
    
    test_request = "Create a login form with remember me"
    
    print("Stage 6: Code Generation - Test Results")
    print("=" * 60)
    
    # Stages 1-5
    context = UIBuilderContext(user_request=test_request, project_dir=".")
    context = analyze_intent(context)
    context.framework = "nextjs-app"  # Mock detection
    context.component_dir = "app/components"
    context = confirm_layout(context)
    context = pick_components(context)
    context = generate_preview(context)
    
    # Stage 6
    context = generate_code(context)
    
    print(f"\nGenerated Files: {len(context.generated_files)}")
    for file in context.generated_files:
        print(f"  • {file.path} ({file.type}, {len(file.content)} bytes)")
